#spring:
#  devtools:
#    livereload:
#      enabled: true
#    restart:
#      enabled: false
#  freemarker:
#    cache: false
#  thymeleaf:
#    cache: false
#    prefix: classpath:/templates/chat/
spring:
  profiles:
    active: default
  redis:
    host: localhost
    port: 6379
  jwt:
    secret: govlepel@$&